service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateAzureLandingZoneDbRecordStep.java
Added init for SubId and TenantId from Landing zone target object
=> [TOAZ-214][Bug] Sub and tenant Id's are not stored when creating a LZ.

service/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java, service/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamService.java, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java, service/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java, service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
- Delete job has the following auth flow:
-  Checks if the landing zone id matches the job id in the flight/job, if not `JobNotFoundException` is thrown
- If the flight is not in a success state, landing zone `delete` action is checked.
- If the flight is in a success state, which means the sam resource is deleted, checks if the user is a valid sam user.
=> [TOAZ-245] New auth flow for delete job results

service/build.gradle, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/ArmManagers.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/ResourceNameGenerator.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactory.java, service/src/main/java/bio/terra/landingzone/library/landingzones/deployment/LandingZoneDeployment.java, service/src/main/java/bio/terra/landingzone/library/landingzones/deployment/LandingZoneDeploymentImpl.java, service/src/main/java/bio/terra/landingzone/library/landingzones/deployment/ResourcesTagMapWrapper.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/AzureResourceTypeUtils.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManager.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourceToDelete.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesDeleteManager.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/deleterules/VmsAreAttachedToVnet.java, service/src/test/java/bio/terra/landingzone/library/landingzones/LandingZoneTestFixture.java, service/src/test/java/bio/terra/landingzone/library/landingzones/TestArmResourcesFactory.java, service/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactoryTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/DeployedLandingZoneDefinitionProviderImplTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/ResourcesDeleteManagerTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/deleterules/BaseDependencyRuleFixture.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/deleterules/ResourceDependencyDeleteRuleTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/deleterules/VmsAreAttachedToVnetTest.java
https://broadworkbench.atlassian.net/browse/TOAZ-227
This PR adds the following to the CromwellBaseResourcesFactory:
* a log analytics workspace
* application insights connected to that workspace
* diagnostic settings for the storage account to turn on audit logging
* monitoring for AKS cluster
2 points of note:
1. the storage account was moved to a prerequisite because it must exist before adding diagnostic settings
2. switching on monitoring for AKS cluster automatically deploys a container insights solution which is untagged, thus the extra hoops when deleting a LZ
=> TOAZ-227 create and use log analytics workspace

service/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamService.java, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/LandingZoneRequest.java, service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
Checked the flight logic - no need to update anything else in library code.
Cleaned up test code while I'm there.
=> [TOAZ-261] Allow the client to set the landing zone id when starting the create job

service/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneSamConfiguration.java, service/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamService.java, service/src/main/java/bio/terra/landingzone/service/iam/SamConstants.java
See https://broadworkbench.atlassian.net/browse/TOAZ-290
Related PRs:
- WSM: https://github.com/DataBiosphere/terra-workspace-manager/pull/928
- terra-helmfile:
This adds list of configurable `landingZoneResourceUsers`, and sets each entry as a `user` on newly-created landing-zone resources in Sam.
Tested on a BEE by making a billing-project in Terra UI. The policies set on the landing-zone are correct:
=> TOAZ-290: add configurable set of users to newly created landing-zone resources

service/src/main/java/bio/terra/landingzone/library/landingzones/management/quotas/BatchQuotaReader.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/quotas/BatchQuotaReaderTest.java
Adds the low-pri node count to the return object of the quota api.
=> [TOA-311] Quota API returns low-priority node count

service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactory.java
Ugh, this eluded me for a while. 
`Boolean.getBoolean(String)` returns true if there is a _System property_ with the given name; we want `Boolean.parseBoolean(String)`. 🤦 
See: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Boolean.html#getBoolean(java.lang.String)
I tested with `CromwellBaseResourcesFactoryTest` -- I see the autoscaling configs in the AKS nodepool now:
=> AJ-768 fix: parse autoscaling param correctly

service/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/DeletedLandingZone.java, service/src/main/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStep.java, service/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java
The access checks to get a completed job was checking for the bp id, which didn't exist on the result.
=> [WOR-812] Include BP id in deleted landing zone result

service/src/main/java/bio/terra/landingzone/common/utils/LandingZoneFlightBeanBag.java, service/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneTestingConfiguration.java, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/LandingZoneRequest.java, service/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneFlightMapKeys.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlight.java, service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-799) and [related design doc.](https://broadworkbench.atlassian.net/wiki/spaces/WOR/pages/2674950157/Azure+Test+Automation)
We need a way to create a landing zone for a limited set of critical path E2E tests (think: create workspace, delete workspace, etc.). To do so, we'll need a landing zone, but do not want to wait the ~10 minutes to spin up a "real" landing zone. In a testing configuration, the ability to "attach" to pre-deployed landing zone resources should suffice.
* Adds a parameter to the creation job, `attach`. When present (and the LZ service configuration allows it), this will skip the creation of landing zone resources in the MRG. The flight still goes through the steps of checking the billing profile …
=> [WOR-799] Add ability to attach to existing azure resources

service/src/main/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStep.java, service/src/test/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStepTest.java
If a landing zone was previously attached for E2E testing, we want to ensure that the Azure resources are not deleted during a subsequent call to delete the landing zone as part of test cleanup. 
* Adds a check against the landing zone properties to determine if the landing zone was created w/`attach: true`. If so, it skips the call to delete the azure resources.
* Adds test coverage for the `DeleteLandingZoneResourcesStep`
=> [WOR-843] Do not delete landing zone resources if the landing zone was attached

.github/workflows/build-and-test.yml, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/DeletedLandingZone.java, service/src/main/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStep.java, service/src/test/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStepTest.java
If the MRG backing a landing zone is removed, deleting the landing zone results in an exception when the deletion code goes to pull in the resources for the landing zone. 
* Handles the `AuthorizationFailed` error from Azure and allows deletion to proceed. Azure gives this error back when the MRG is deleted rather than a 404-type error. Given that the IAM on the MRG is not alterable by users due to deny assignments, we can assume that the MRG has been removed and can proceed forward with deletion.
=> [WOR-861] Do not fail deletion if backing MRG is inaccessible

.github/dependabot.yml
Dependabot should scan for upgraded libs so we get the latest security updates.
=> [WOR-894] Add dependabot config for LZS

service/build.gradle
Azure Identity 1.8.2 has an upgraded msal4j which in turn has an upgraded json smart lib. 
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-872)
=> [WOR-872] Pull in azure-identity 1.8.2 to mitigate json-smart CVE

service/build.gradle, testharness/build.gradle
json-smart 2.4.8 is still pinging the sourceclear scans for this library even after upgrading to the latest azure-identity. This is likely because an upstream dep of azure-identity is still pulling in 2.4.8 transitively even though azure-identity has upgraded itself. I'm explicitly excluding the dep in both `service` and `testharness` and pulling in 2.4.10. It looks like the next azure-sdk should fix this issue so we should look into removing this workaround once that is released in May.
=> [WOR-952] Exclude vulnerable version of json-smart

service/build.gradle, service/src/main/java/bio/terra/landingzone/common/utils/LandingZoneFlightBeanBag.java, service/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneProtectedDataConfiguration.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/ArmManagers.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManager.java, service/src/main/java/bio/terra/landingzone/stairway/flight/CromwellStepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/ProtectedDataStepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/StepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlight.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateSentinelRunPlaybookAutomationRule.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateSentinelStep.java, service/src/test/java/bio/terra/landingzone/library/landingzones/LandingZoneTestFixture.java, service/src/test/java/bio/terra/landingzone/library/landingzones/TestArmResourcesFactory.java, service/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/DeployedLandingZoneDefinitionProviderImplTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/deleterules/BaseDependencyRuleFixture.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/BaseStepTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateSentinelRunPlaybookAutomationRuleTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateSentinelStepTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateVnetStepTest.java, service/src/test/resources/application-test.yml, settings.gradle, testharness/src/main/resources/application.yml
https://broadworkbench.atlassian.net/browse/WOR-941
This PR introduces:
-Sentinel as a part of a protected landing zone 
-Automation rule for slack notification. This rule triggers playbook (Logic App) in a "central" Sentinel.
-Configuration which points to a certain playbook (Logic App). This configuration doesn't have any values here since it should be set in WSM (at least while we are using amalgamated approach).
=> WOR-941 Deploy sentinel to protected data LZ log analytics workspace in customer MRG

buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle, testharness/build.gradle
Ticket: [WOR-1001](https://broadworkbench.atlassian.net/browse/WOR-1001)
* bump TCL to use non-vulnerable version of jose4j
* `./gradlew build` was failing for me with the following error:
```
A problem was found with the configuration of task ':testharness:jacocoTestReport' (type 'JacocoReport').
- Gradle detected a problem with the following location: '/Users/mtalbott/ws/broad/terra-landing-zone-service/service/build/classes'.
Reason: Task ':testharness:jacocoTestReport' uses this output of task ':service:compileTestJava' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
This was happening on `main` as well as my branch, but adding the `dependsOn` to `:testharness:jacocoTestReport` …
=> [WOR-1001] Bump jose4j

scripts/write-config.sh, service/render-test-config.sh, service/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneAzureConfiguration.java, service/src/main/java/bio/terra/landingzone/library/configuration/stairway/LandingZoneStairwayConfiguration.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/AggregateLandingZoneResourcesStep.java, service/src/test/java/bio/terra/landingzone/app/StartupInitializer.java, service/src/test/java/bio/terra/landingzone/app/TestBeanConfig.java, service/src/test/java/bio/terra/landingzone/library/landingzones/AzureIntegrationUtils.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateStorageAccountStepTest.java, service/src/test/resources/application-test.yml
a clean re-application of the changes originally in [this PR](https://github.com/DataBiosphere/terra-landing-zone-service/pull/124)
In addition, this cleans up the azure config setup, so that the spring based `LandingZoneAzureConfiguration` and the existing `AzureIntegrationUtils` used in tests look for the same properties.
[WOR-995](https://broadworkbench.atlassian.net/browse/WOR-995)
This is to add integration tests for the new stairway code path to create landing zone resources (CreateLandingZoneResourcesFlight).
I attempted to put these in the testharness project, but in the end it required more resources that were in the primary service project, so I abandoned that idea
This doesn't test creating the entire landing zone. The existing integration tests don't cover this, and it would …
=> WOR-995 reapply changes for stairway integration tests

service/src/main/java/bio/terra/landingzone/stairway/flight/ProtectedDataStepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksLogSettingsStep.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksLogSettingsStepTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/ResourceStepFixture.java
This PR adds configuration to AKS in LZ to ship its logs into long term storage account.
=> WOR-1028 Ship Azure AKS logs directly to centralized storage

.github/dependabot.yml
Dependabot PRs are becoming noisy to deal with on a daily basis. This shifts the updates to a weekly cadence. 
NOTE:
We had discussed limiting the updates for some of our noisier libs. I grepped through the git history and gave it a try with this [commit](https://github.com/DataBiosphere/terra-landing-zone-service/pull/140/commits/f1979afae0bfc0bcead0e5c7f446f4f4c95ef831). I think we should try reducing the cadence to weekly first, before silencing the noisier offenders.
=> [WOR-1036] Run dependabot weekly

README.md, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactory.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/AksParametersValidator.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/BlobCorsParametersValidator.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/InputParameterValidator.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/InputParametersValidationFactory.java, service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/StorageAccountSkuTypeValidator.java, service/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneDefaultParameters.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateStorageAccountStep.java, service/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/StorageAccountSkuTypeValidatorTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateStorageAccountStepTest.java
This PR Introduces new parameter for LZ creation:
-STORAGE_ACCOUNT_SKU_TYPE manages type of storage account. Default value is "Standard_LRS" (Standard Locally Redundant Storage).
=> WOR-991 Make LZ Storage Account Redundancy Configurable and set new default

service/build.gradle, service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/LandingZoneDiagnosticSetting.java, service/src/main/java/bio/terra/landingzone/stairway/flight/ProtectedDataStepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateStorageAuditLogSettingsStep.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java
The Azure sdk after 2.24 but before 2.28 broke creating diagnostic settings on storage accounts. This was particularly insidious because the SDK call would succeed, but no setting would be created in the MRG.
* Pulls in a fixed version of the SDK
* Adds a test that reads back the diagnostic settings from the MRG and ensures the expected settings are present.
=> [WOR-1057] Add test for storage account diagnostic settings

service/src/main/java/bio/terra/landingzone/stairway/flight/utils/AlertRulesHelper.java
Alert rule templates include a description, it should be included in the instantiated alert rule.
=> [WOR-1114] Include alert rule description from template

service/src/main/java/bio/terra/landingzone/common/utils/LandingZoneFlightBeanBag.java, service/src/main/java/bio/terra/landingzone/library/LandingZoneManagerProvider.java, service/src/main/java/bio/terra/landingzone/library/configuration/AzureCustomerUsageConfiguration.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManager.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlight.java, service/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactoryTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/ManagedNetworkWithSharedResourcesFactoryTest.java, service/src/test/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManagerIntegrationTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java, service/src/test/resources/application-test.yml, testharness/src/main/resources/application.yml, testharness/src/test/resources/application-test.yml
Original POC - https://broadworkbench.atlassian.net/browse/WOR-829
Story - https://broadworkbench.atlassian.net/browse/WOR-1103
Azure documentation - https://learn.microsoft.com/en-us/partner-center/marketplace/azure-partner-customer-usage-attribution#use-resource-manager-apis
This change introduces new header attribute with specific value which will be injected into all Azure resource managers.
=> WOR-1103 Emit usage data for azure resources

service/src/main/java/bio/terra/landingzone/stairway/flight/CromwellStepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksCostOptimizationDataCollectionRulesStep.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStepTest.java
K8s cost optimization settings requires following parameter 'useAADAuth'=true. The cost optimization settings won't be provisioned correctly without this parameter. At the same time this parameter breaks K8s monitoring. So, temporarily disabling cost optimization step to unblock K9s monitoring.
This PR:
-temporarily remove K8s cost optimization step from LZ flight.
=> WOR-1146 Disable K8s cost optimization settings for monitoring

service/src/main/java/bio/terra/landingzone/common/VirtualNetworkLinkResourceHelper.java, service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesDeleteManager.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateVirtualNetworkLinkStep.java
This PR uses resource specific deletion instead of generic one. This is temporary solution until the issue is fixed in Java SDK.
=> WOR-1164 Mitigate deletion of virtualNetworkLink

buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle
Ticket: https://broadworkbench.atlassian.net/browse/WOR-1113
As far as I can tell by looking at the dependency tree, this will update `grpc-xds`, which is a transitive dependency brought in by `terra-common-lib`.
Related to https://github.com/DataBiosphere/terra-common-lib/pull/114.
=> Update tcl for io.grpc:grpc-xds (WOR-1113).

service/src/test/java/bio/terra/landingzone/library/landingzones/AzureIntegrationUtils.java
The terra-dev sub often runs out of batch accounts due to quota limitations. This sub is really intended for housing dev related infrastructure like long term log storage and app registrations, not dev testing. The dsp-azure-testing sub is more suited for this purpose and has a higher batch account quota.
=> Point at a different sub with more batch quota

service/src/main/java/bio/terra/landingzone/common/utils/HttpResponseUtils.java, service/src/main/java/bio/terra/landingzone/stairway/flight/CromwellStepsDefinitionProvider.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksCostOptimizationDataCollectionRulesStep.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/EnableAksContainerInsightsStep.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/EnableAksContainerLogV2Step.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksCostOptimizationDataCollectionRulesStepTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStepTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/EnableAksContainerInsightsStepTest.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/ResourceStepFixture.java
This PR turn on K8s cost optimization settings for monitoring. Especially it 1) sets monitoring interval 30 minutes long and 2) turn off namespace filtering 3) enables syslog collection.
In general, to achieve this we need to create: 1) data collection rule 2) data collection rule association and 3) enable K8s monitoring. To enable monitoring, we need to apply special "omsagent" profile which points to a certain log analytics workspace and has following property "useAADAuth=true". Earlier we applied this profile during K8s creation. But it turns out that using this parameter "useAADAuth=true" breaks K8s logging. So, it was removed and as a result we disable this cost optimization settings. It turns out that this parameter is required, but instead we need to enable k8s monitoring later …
=> WOR-1147 Enable K8s cost optimization settings for monitoring

service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksLogSettingsStep.java
Setting the log retention settings during AKS cluster creation is causing failures due to an API deprecation from Azure (see this doc).
=> Set retention days to 0 to handle api deprecation

service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesDeleteManager.java
The previous version of SDK has issue with the deletion of a resource with the following type 'privateDnsZones/virtualNetworkLinks' when using generic deletion API. This issue was resolved in the latest (2.30.0) version.
This PR:
-switch to the latest version (2.30.0)
-revert deletion mechanism to use generic deletion API.
=> WOR-1166 Switch to generic resource deletion for this resource type 'virtualNetworkLink'

service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactory.java, service/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneDefaultParameters.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java, service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/KubernetesClientProviderImpl.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStepTest.java
Microsoft security guidelines now require an additional AAD authentication step when using user credentials for AKS. This and related PRs are to switch Terra services to using admin credentials and set a default AAD group when the AKS cluster is created.
=> [WOR-1218] Use AKS AAD integration

service/build.gradle
`javax.servlet:jstl:1.2` was flagged as having a known security vulnerability in a recent scan, and downstream clients which depend on Landing Zone Service are also impacted (e.g. WSM). This library was included when this service was first split out into its own repo, but does not appear to be used anywhere in the code.
=> [PF-2972] Remove unused dependency

service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStepTest.java
Set up custom name for the node resource group for AKS cluster to limit it's length and prevent Azure error during AKS creation.
Earlier name of the node resource group was generated automatically somewhere down the SDK and was built from 4 different parts divided by underscore: 1) prefix 2) name of the MRG 3) AKS resource name 4) region. Name of the MRG (managed resource group) can vary and as a result the node resource group can exceed the limit of 80 characters. Now we are setting it manually during creation.
=> WOR-1213 Long Azure MRG name causes landing zone to fail to create

service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java, service/src/main/java/bio/terra/landingzone/stairway/flight/exception/ResourceCreationException.java, service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStepTest.java
Creation of AKS is a long running operation. In case Stairway by some reason resumes landing zone flight at the AKS creation step we need to handle conflict (because we send 2nd request) and poll for AKS provisioned status.
=> WOR-1233 Landing Zone creation steps should be idempotent.

foundation.yaml
This is a functional no-op PR that just adds a metadata file to the LZ service repo that is used to ingest LZ service into [DSP's backstage instance](https://backstage.dsp-devops.broadinstitute.org/catalog?filters%5Bkind%5D=component&filters%5Buser%5D=owned). Backstage is an internal platform tool that can be used for a lot of SDLC processes and improving Dev experience. DevOps is just starting to experiment with this as a means to make getting a new service stood up in the terra environments and through the prod readiness checklist easier.
But we also want all our existing services to be in the system so they can get any benefits.
=> DDO-3198 Add Metadata Yaml File to to ingest LZ service into DSP backstage

library/src/main/java/bio/terra/landingzone/common/utils/LandingZoneFlightBeanBag.java, library/src/main/java/bio/terra/landingzone/library/AzureCredentialsProvider.java, library/src/main/java/bio/terra/landingzone/library/LandingZoneManagerProvider.java, library/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneAzureConfiguration.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlight.java
Workspace Manager integration tests fail with the current LZ lib as WSM doesn't wire up the needed Azure credentials/login in it's CI pipeline. I've introduced a backwards compatibility layer to keep things functional there and unblock things. We will want to remove this shim once LZS is deamalgamated.
=> Add a backwards compatible layer for Azure creds

library/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/BaseResourceCreateStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresqlDbStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/exception/utils/ManagementExceptionUtils.java, library/src/test/java/bio/terra/landingzone/library/landingzones/TestArmResourcesFactory.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresqlDbStepTest.java, library/src/test/resources/application-test.yml
This PR:
- Handles "Long running operation Failed or Cancelled" issue during Postgres provisioning. As a result, corresponding step could be retried. Fix is based on the following shape of the error:
`{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"InternalServerError\",\"message\":\"An unexpected error occured while processing the request. Tracking ID: '8a04238e-7145-42d6-a71e-8a82d6f9f819'\"}]}}
`
- Switch to eastus region for integration test since we have issues in southcentral region related to Postgres provisioning. But this issue is different from what was mentioned above.
- Extends logging of exception information.
=> WOR-1339 Landing zone intermittently fails to create

.github/workflows/build-and-test.yml, .github/workflows/linter-tests.yml, .github/workflows/workflow-tester.yml, buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle, library/build.gradle, testharness/build.gradle
SonarCloud provides us the needed coverage and Spotbugs is busted w/6.0 as the sarif files are not compatible with the codeql-action.
=> [WOR-1402] Remove spotbugs

library/src/main/java/bio/terra/landingzone/library/landingzones/definition/DefinitionVersion.java, library/src/main/java/bio/terra/landingzone/library/landingzones/deployment/LandingZoneTagKeys.java, library/src/main/java/bio/terra/landingzone/library/landingzones/deployment/ResourcePurpose.java, library/src/main/java/bio/terra/landingzone/library/landingzones/deployment/SubnetResourcePurpose.java, library/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesReaderImpl.java, library/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java
This PR:
- Replaces usage of ExpandableStringEnum(deprecated) with Java's enum.
=> WOR-1433 [LZS] Remove usage of deprecated ExpandableStringEnum class.

.github/dependabot.yml
To cut down on the number of individual PRs, group minor release updates (which should have no breaking changes) together.
=> [NO TICKET] Group dependabot updates.

.github/dependabot.yml
Follow-up to https://github.com/DataBiosphere/terra-landing-zone-service/pull/387 to exclude problematic upgrades (we have tickets for them) and include the long-lived JIRA ticket on dependabot PRs.
=> [NO TICKET] Add ticket number and prevent problematic updates (dependabot)

library/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateAzureLandingZoneDbRecordStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlight.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateAzureLandingZoneDbRecordStepTest.java
[WOR-1436](https://broadworkbench.atlassian.net/browse/WOR-1436)
This PR is for actually persisting the region to the landing zone.
It also cleans up access of the landing zone DAO, to get it from the flight context => `LandingZoneFlightBeanBag`, instead of the constructor.
[WOR-1436]: https://broadworkbench.atlassian.net/browse/WOR-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WOR-1436: persist region

library/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlight.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlightTest.java
Adding the region to the landing zone created a new dependency on the `GetManagedResourceGroupInfo` step when attaching a landing zone to existing resources.
This adds the step in directly in the case that exists in order to support testing, in order to avoid changing the main code path, and so minimize the changes that need to be tested in this PR.
=> WOR-1478: get MRG when attaching a landing zone

.github/workflows/tag-publish.yml
This PR tries to fix issue related to `releaseVersion` update in settings.gradle. This value hasn't been updated since mid. Dec. 2023.
So, this PR:
-updates bumper action version from 0.0.6 to 0.3.0
My initial assumptions that we need to reuse bumper action from `tag.yaml` instead might be not correct. I decided to start with simple version update. WSM uses the same pattern: bumper action from "tag.yaml" is used in contract testing workflows and build workflow has its own job which invokes bumper action.
Current issue also might be related to this [bug](https://github.com/DataBiosphere/terra-billing-profile-manager/pull/362). Also, there was a discussion in [slack](https://broadinstitute.slack.com/archives/C029LTN5L80/p1701790454495569)
=> WOR-1511 Fix bumptagbot in LZS

.github/workflows/tag-publish.yml
Setup different github action for GCR authentication. The specified secret has been migrated already in this [PR](https://github.com/broadinstitute/terraform-ap-deployments/pull/1376)
=> WOR-1515 Port Vault Secrets to Github Actions Secrets with Atlantis.

buildSrc/src/main/groovy/bio.terra.landingzone.java-spring-app-conventions.gradle
https://broadworkbench.atlassian.net/browse/WOR-1535
Our current version of Spring Boot is [3.1.2](https://github.com/DataBiosphere/terra-landing-zone-service/blob/4a729a87adbabea21fde25a91162de329136b845/buildSrc/build.gradle#L18), which [brings in postgresql 42.6.0](https://github.com/spring-projects/spring-boot/blame/v3.1.2/spring-boot-project/spring-boot-dependencies/build.gradle#L1096-L1102).
To mitigate a security vulnerability, we must instruct Spring Boot use a non-vulnerable version.
I first tried upgrading our TCL to see if that would fix things but this had no impact: the Spring Boot pin was both necessary and sufficient, so I will pursue the TCL upgrade separately as it's a larger change.
=> [WOR-1535] Spring Boot dependency: pin postgresql to 42.7.2

service/src/main/java/bio/terra/lz/futureservice/TestController.java
This is just some dummy change to validate `Broad Bot` bump activity. It turns out that `Broad Bot` lost admin permission for this repository. It's not clear when, but `bump` stopped working in the mid of December 2023.
I granted admin permission to the `Broad Bot`. This is a test to validate whether `Broad Bot` will bump version. Want to quickly validate if granting permission resolve bump issue. Change in code is pretty valid, since that controller should be eventually deleted.
=> [NO TICKET] Broad bot bump test

.github/dependabot.yml, buildSrc/build.gradle, buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle, buildSrc/src/main/groovy/bio.terra.landingzone.java-spring-conventions.gradle, library/build.gradle, library/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateLandingZoneFederatedIdentityStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/EnableAksContainerLogV2Step.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateLandingZoneFederatedIdentityStepTest.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/EnableAksContainerLogV2StepTest.java, service/build.gradle, testharness/build.gradle
https://broadworkbench.atlassian.net/browse/WOR-1587
**Dependency Upgrades**
This PR undertakes a number of dependency upgrades:
- Spring Boot 3.1.2 -> 3.2.3
- `io.kubernetes:client-java` 20.0.0-legacy -> 20.0.1
- This upgrade contains breaking changes: optional parameters are now consolidated into a single object, and we must explicitly execute our requests.
- Christina started down the path of addressing them in : [[WOR-1448]: Bump the minor-patch-dependencies group with 8 updates by dependabot[bot] · Pull Request #423 · DataBiosphere/terra-landing-zone-service](https://github.com/DataBiosphere/terra-landing-zone-service/pull/423), but we decided to break this out due to the heightened risk.
- `bio.terra:terra-common-lib` 1.0.10-SNAPSHOT -> 1.1.0-SNAPSHOT
- This upgrade contains TCL's …
=> [WOR-1586] Spring Boot 3.2.3, k8s client 20.0.1, TCL 1.1.0

library/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAppInsightsStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/postgres/CreatePostgresqlDbAdminStep.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/postgres/CreatePostgresqlDbAdminStepTest.java
[Related ticket](https://broadworkbench.atlassian.net/browse/WOR-1590)
* The wrong identifier is being stored for proper admin resource deletion.
* App insights is not resilient to `400 Bad Request`s when the log analytics workspace is unavailable. Something similar happens during sentinel wireup, which we workaround with retries.
=> [WOR-1590] Use correct resource ID during PG admin creation, retry on app insights 400

.github/workflows/tag-publish.yml
I left `pull_request` option since publishing custom app version might be really helpful for BEE deployment.
Instead, I added condition for publishing artifacts.
=> WOR-1598 Stop publishing unapproved changes in LZS.

.github/dependabot.yml, CONTRIBUTING.md, buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle, library/build.gradle, service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java
This TCL version includes KubePodListener fixes to work with the non-legacy k8s client.  Related PR: DataBiosphere/terra-common-lib#174
Instruct Dependabot to ignore k8s client upgrades.  The client is publishing legacy and non-legacy versions, and Dependabot tries to update to the latest published version.
Finished wiring in srcclr plug-in (an additional block of config was required to run it), added instructions for running scans off of local code and feature branches.
=> [WOR-1448] Upgrade TCL 1.1.1 -> 1.1.6

buildSrc/src/main/groovy/bio.terra.landingzone.java-spring-conventions.gradle
I've added a pin to override Spring Boot 3.2.3's netty dependencies versioned at [io.netty:netty-handler:4.1.107.Final](https://github.com/spring-projects/spring-boot/blob/v3.2.3/spring-boot-project/spring-boot-dependencies/build.gradle#L1084-L1090) which contain vulnerabilities. Other dependencies may also pull in these transitive dependencies, but the Spring dependency manager version clobbers them all.
If Spring Boot upgrades this on their end in a future release (they haven't done so yet in 3.2.4), you can remove the pin.
Here is a [GHA Veracode](https://github.com/broadinstitute/dsp-appsec-sourceclear-github-actions/actions/runs/8545717883/job/23414607450) scan that I manually triggered off of this feature branch.
Comparison against the last scan run off of the `main` branch:
- Risk …
=> [WOR-1448] Pin Spring dependency manager's netty version to 4.1.108.Final

service/src/main/java/bio/terra/lz/futureservice/app/service/LandingZoneAppService.java, service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java, service/src/test/java/bio/terra/lz/futureservice/common/fixture/AzureLandingZoneFixtures.java
Region is required by WSM, it must be included in LZ details returned from the service.
=> [WOR-1127] Include region in landing zone responses

service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java
This test was flaky and I disabled it to unblock a hotfix.  `Instant.now().atOffset(ZoneOffset.UTC).toString()` which we use for the assertion in this test can return a _slightly_ different result than the internal serialization mechanisms LZS uses when it renders the timestamp. Since we shouldn't use `now()` in tests anyway (that always leads to flakiness), I've opted to shift to a hardcoded date that consistently matches and re-enable the test.
=> Reenable test

service/src/main/resources/application.yml
Jira [ticket](https://broadworkbench.atlassian.net/browse/WOR-1658)
Landing zone required configuration was missing. As a result landing zone falls back to the default value for node pool VM size which is 'Standard_A2_v2 ' instead of 'Standard_D4as_v5'. As a result, the relay listener application was struggling to start and preventing WDS/WORKFLOW application to respond.
=> WOR-1658 Workflows app will not start when the de-amalgamated LZS is enabled

service/src/main/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiController.java, service/src/main/java/bio/terra/lz/futureservice/common/utils/RequestQueryParamUtils.java, service/src/main/resources/api/service_openapi.yaml, service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java, service/src/test/java/bio/terra/lz/futureservice/common/utils/RequestQueryParamUtilsTest.java
Regular validation works. For instance, in case instead of UUID some other string provided like "abs". But...
In certain cases, the "billingProfileId" parameter may be null, even if the original query parameter of the GET request contains a value for it. This situation can arise during Tomcat server request parameter validation, even before validating the type (UUID) of the parameter. For instance, the query string parameter’s value might be sanitized if it contains forbidden characters. It is important to distinguish between scenarios where the parameter was initially supplied and when it was subsequently sanitized.
=> [WIP] WOR-1662 [LZ Pentest] User input for billingProfileId is not validated for get LZ endpoint.

service/src/main/java/bio/terra/lz/futureservice/app/common/http/filter/CacheControlResponseHeaderFilter.java, service/src/test/java/bio/terra/lz/futureservice/app/controller/ControllerResponseHeaderTest.java, service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java, service/src/test/java/bio/terra/lz/futureservice/common/TestEndpoints.java
Now API response returns following caching directives:
-Cache-control: no-store
-Pragma: no-cache
=> WOR-1663 [LZ Pentest] Endpoints should return caching directives.

library/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java, library/src/main/java/bio/terra/landingzone/service/iam/SamConstants.java, library/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java, library/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneFlightMapKeys.java, library/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java, library/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
https://broadworkbench.atlassian.net/browse/WOR-1765
This PR simplifies and consolidates the permission check for create and delete landing zone jobs. There are 2 subtle changes I want to call out
1. The permission check always throws forbidden, never not found, to prevent information leaks. A related fixed leak would output the billing profile id of a job if the user did not have access
2. Create/delete jobs need the billing profile id as an input parameter which will break any jobs in flight. To avoid that I can release a PR ahead of time that starts populating the input parameter. But I want thumbs on this PR before deciding the best approach for roll out.
=> WOR-1765 check spend-profile.read_job_result for lz create/delete jobs

library/build.gradle
Ticket: [WOR-1448](https://broadworkbench.atlassian.net/browse/WOR-1448)
* https://github.com/DataBiosphere/terra-landing-zone-service/pull/490 tried to update the liquibase gradle plugin dependency to 3.0.0 but caused build failures. Upon investigation, we do not appear to be using this plugin at all as LZS uses TCL's [LiquibaseMigrator](https://github.com/DataBiosphere/terra-common-lib/blob/db8a959c2b6185755ed48917e9951c97f8691d8e/src/main/java/bio/terra/common/migrate/LiquibaseMigrator.java) to migrate its database when it starts up ([source](https://github.com/DataBiosphere/terra-landing-zone-service/blob/860cdf1814413c8ba53d76ea32ba47530506f3a0/library/src/main/java/bio/terra/landingzone/library/LandingZoneMain.java#L20-L24)) similar to our other services …
=> [WOR-1448] Remove org.liquibase.gradle dependency

service/src/main/resources/application.yml, service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java
Standard_D4as_v4 is not allocating in scus,  Standard_D4s_v3 works in my testing.
=> [WOR-1807] Change default AKS machine type in south central US

library/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/LandingZoneStepsDefinitionProviderFactory.java, library/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/ReferencedLandingZoneStepsDefinitionProvider.java, library/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/StepsDefinitionFactoryType.java, library/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/InputParametersValidationFactory.java, library/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/ReferencedVNetValidator.java, library/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneDefaultParameters.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ArmResourceType.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/BaseReferencedResourceStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ReferencedAksStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ReferencedAppInsightsStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ReferencedBatchStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ReferencedRelayNamespaceStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ReferencedStorageStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/ReferencedVnetStep.java, library/src/main/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/SharedReferencedResourceStep.java, library/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/StepsDefinitionFactoryTypeTest.java, library/src/test/java/bio/terra/landingzone/library/landingzones/definition/factories/validation/ReferencedVNetValidatorTest.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/reference/resource/step/BaseReferencedResourceStepTest.java
In this PR: 
-  A new LZ (Landing Zone) definition called “Referenced Landing Zone.”
It is designed for scenarios where data plane resources are deployed via a Service Catalog managed application.
- The definition does not deploy any resources.
Instead, it checks for the existence of the following resources:
AKS cluster, Storage account, Batch account, App Insights, VNet, Azure Relay, PostgreSQL flexible server
It assigns the necessary tags to classify these resources as LZ resources.
- The definition does not impose any constraints on how these resources are configured.
=> [TOAZ-369] Referenced LZ definition

.github/workflows/build-and-test.yml, .github/workflows/verify_consumer_pacts.yaml, service/src/main/resources/api/swagger-ui.html
**Description:**
This PR adds a Content Security Policy (CSP) header to the Landing Zone Service Swagger page to enhance security by reducing the risk of cross-site scripting (XSS) and data injection attacks.
**Changes:**
- Added CSP header to the Swagger page response using the most common directives:
- **default-src** _the default policy for loading javascript, images, CSS, fonts, AJAX requests, etc_
- **script-src** _defines valid sources for javascript files_
- **style-src** _defines valid sources for CSS files_
- **img-src** _defines valid sources for images_
- **connect-src** _defines valid targets for XMLHttpRequest (AJAX), WebSockets, and EventSource._
- Configured the header to allow necessary resources, using `unsafe-inline` to enable inline scripts and styles where needed.
- …
=> [WOR-1824]: Add CSP Header to Swagger Page

service/src/main/java/bio/terra/lz/futureservice/app/common/http/filter/StrictTransportSecurityHeaderFilter.java, service/src/test/java/bio/terra/lz/futureservice/app/controller/ControllerResponseHeaderTest.java
Ticket: [WOR-1825](https://broadworkbench.atlassian.net/browse/WOR-1825)
* Implementation inspired by Sergiy's approach to set other headers on LZS responses - https://github.com/DataBiosphere/terra-landing-zone-service/pull/478
* Header values taken from https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#examples and seemed to be a reasonable choice
[WOR-1825]: https://broadworkbench.atlassian.net/browse/WOR-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WOR-1825] Set Strict-Transport-Security header on LZS responses

foundation.yaml, service/gradle/publishing.gradle
Ticket: https://broadworkbench.atlassian.net/browse/CORE-44
**Description:**
This PR upgrades the base image from jre:17-distroless to jre:17-12-distroless to fix a security vulnerability. Service compatibility has been checked, and tests have been run to ensure everything works as expected.
It also includes an update of the codebase owner to the new team: `broad-core-services`
**Infosec Discussion:**
Reference: [Message from David Bernick in #dsp-engineering.](https://broadinstitute.slack.com/archives/C0DSD41QT/p1728328182615109)
=> [CORE-44] Upgrade Base Image to jre:17-12-distroless for Security Fix

.github/dependabot.yml
Dependabot automatically tags an associated ticket and the workspaces team. The ticket was moved from WS to CORE; this PR updates the ticket and which team is tagged on dependabot updates.
=> [CORE-69] Move automatic dependency updates to CORE from Workspaces

.github/workflows/tag-publish.yml
The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
More info here: https://github.com/marketplace/actions/cache
=> CORE-246 Upgrading to cache v4 

service/src/main/resources/application.yml
Ticket: [CORE-275](https://broadworkbench.atlassian.net/browse/CORE-275)
* Set correct Azure environment for case statement in `AzureConfiguration` which looks for "AzureCloud" not "AZURE" ([source](https://github.com/DataBiosphere/terra-landing-zone-service/blob/76621c4fe642e617daa8e12a136ce24bb61601b8/library/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneAzureConfiguration.java#L42-L44))
[CORE-275]: https://broadworkbench.atlassian.net/browse/CORE-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CORE-275] Use correct value for azureEnvironment

buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle, library/build.gradle, library/src/main/java/bio/terra/landingzone/library/configuration/stairway/LandingZoneStairwayConfiguration.java
https://broadworkbench.atlassian.net/browse/CORE-391
Update terra-common-lib 1.1.11 -> 1.1.38
Update k8s client-java 20.0.1 -> 23.0.0, which matches the version in TCL 1.1.38
=> CORE-391: update TCL and k8s client

library/build.gradle, library/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamService.java, library/src/test/java/bio/terra/landingzone/service/iam/LandingZoneSamServiceTest.java, library/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java, service/src/main/java/bio/terra/lz/futureservice/app/service/status/BaseStatusService.java, service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java, service/src/test/java/bio/terra/lz/futureservice/app/controller/PublicApiControllerTest.java, service/src/test/java/bio/terra/lz/futureservice/pact/consumer/SamServiceConsumerPactTest.java, service/src/test/java/bio/terra/lz/futureservice/pact/provider/LandingZoneServicePactProviderTest.java
#546, as part of upgrading terra-common-lib, upgraded Spring Boot.
The newer version of Spring Boot deprecates `@MockBean` in favor of `@MockitoBean` and logs warnings during compilation when `@MockBean` is used.
This PR switches all usages of `@MockBean` to `@MockitoBean`.
It also updates the Sam client library version. The version previously used was very old. The newer version requires some syntax changes for compatibility.
=> CORE-391: update to latest Sam client; MockBean->MockitoBean

buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle
https://broadworkbench.atlassian.net/browse/CORE-376
Update TCL to get its fix for the "failed to export spans" error.
See https://github.com/DataBiosphere/terra-common-lib/pull/229
=> CORE-376: turn off double-tracing and 'failed to export spans' error
