- testharness/src/main/resources/application.yml
Clean up code: refer to landing zone instead of policy
> Clean up code

- scripts/postgres-init.sql
- service/build.gradle
- service/src/main/java/bio/terra/landingzone/library/LandingZoneMain.java
- service/src/main/java/bio/terra/landingzone/library/configuration/LandingZoneJobConfiguration.java
- service/src/main/java/bio/terra/landingzone/library/configuration/stairway/LandingZoneStairwayConfiguration.java
- service/src/main/java/bio/terra/landingzone/library/configuration/stairway/LandingZoneStairwayDatabaseConfiguration.java
- service/src/main/java/bio/terra/landingzone/library/stairway/StairwayService.java
- service/src/test/resources/application-test.yml
- testharness/src/main/java/bio/terra/landingzone/app/Main.java
- testharness/src/main/resources/application.yml
- testharness/src/test/resources/application-test.yml
Add initialization for Stairway database
> Initialize Stairway database

- service/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java
Add qualifier to resolve ambiguity.
> Update bean configuration

- README.md
- service/build.gradle
Update sonarqube configuration
> Update sonarqube configuration

- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java
> Tiny refactoring

- service/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java
- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java
- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/StartLandingZoneCreation.java
- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/model/StartLandingZoneDeletion.java
- service/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java
Operations return new object types with the landing zone information.
> [TOAZ 250] Changed the return type for start create and delete operations and return the lz id.

- service/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java
- service/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java
TOAZ-246 Use the billing profile to check if the user is authorized to get the job results
> Use the billing profile to check if the user is authorized

- service/src/main/java/bio/terra/landingzone/library/landingzones/management/AzureResourceTypeUtils.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManager.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/quotas/BatchQuotaReader.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/quotas/QuotaProvider.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/quotas/ResourceQuota.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/quotas/ResourceQuotaReader.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/quotas/ResourceTypeNotSupportedException.java
- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/TestUtils.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/management/AzureResourceTypeUtilsTest.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManagerIntegrationTest.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/management/LandingZoneManagerTest.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/management/quotas/BatchQuotaReaderTest.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/management/quotas/QuotaProviderTest.java
- service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
- Adds the ability to return quota information for lz resources.
- Initial support for batch accounts only. 
- More resources can be added as needed.
> [TOAZ-271] Quota information for LZ resources

- buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle
- service/build.gradle
- service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
- testharness/build.gradle
Bumped SAM and common lib clients to the latest versions,
updated ARM libs to 2.18, azure core and azure identity to match common lib,
postgresql to 42.5.1.
> [TOAZ-257] Address DefectDojo findings in LZ service

- service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateAzureLandingZoneStep.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/exception/LandingZoneCreateException.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/exception/LandingZoneProcessingException.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/exception/translation/BatchAccountQuotaExceedExceptionRule.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/exception/translation/ExceptionMatchingRule.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/exception/translation/FlightExceptionTranslator.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/exception/translation/BatchAccountQuotaExceedExceptionRuleTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/exception/translation/ExceptionFixtures.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/exception/translation/FlightExceptionTranslatorTest.java
https://broadworkbench.atlassian.net/browse/TOAZ-260
This PR introduces exception translation which maps original flight exception into new one with appropriate message information. Translation is based on the set of predefined rules. Currently there is only one rule related to Batch quota account issue.
> TOAZ-260 Return a relevant error message when flight fails due to quota limits

- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java
- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/exception/LandingZoneDatabaseException.java
- service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
Implemented handling internal data access exceptions thrown in Landing zone DAO.
> [TOAZ-312] LZ creation API returns SQL data in the exception message.

- service/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamClient.java
- service/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamService.java
- service/src/test/java/bio/terra/landingzone/service/iam/LandingZoneSamServiceTest.java
- service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
1. Separated client and config into SamClient class.
2. Added unit tests for Sam Service logic.
> [TOAZ-292] Add unit tests for LandingZoneSamService

- service/src/main/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneService.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneStepsDefinitionProviderFactory.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/StepsDefinitionFactoryType.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlight.java
- service/src/test/java/bio/terra/landingzone/service/landingzone/azure/LandingZoneServiceTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/StepsDefinitionFactoryTypeTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlightTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightTest.java
https://broadworkbench.atlassian.net/browse/WOR-989
> WOR-989 Stairway path for LZ creation minor issues

- gradle/wrapper/gradle-wrapper.properties
I decided to try upgrading Gradle to see if it helps with https://github.com/DataBiosphere/terra-landing-zone-service/pull/110. Regardless of whether or not it helps, it seems like upgrading is a good idea given that everything passed.
> [WOR-985] Upgrade Gradle

- service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourceToDelete.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesDeleteManager.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/ProtectedDataStepsDefinitionProvider.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/TestArmResourcesFactory.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/BaseIntegrationTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/LandingZoneRequestFixtures.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/TestDeleteLandingZoneResourcesFlight.java
- service/src/test/resources/application-test.yml
This PR:
-Adjust delete to handle deletion for ProtectedData LZ
-Add test for deletion of ProtectedData LZ
> WOR-1002 Adjust existing delete mechanism to handle protected data landing zone

- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresLogSettingsStep.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresLogSettingsStepTest.java
Adjust log diagnostic settings for flexible version of postgres
> WOR-1050 Adjust log diagnostic settings for flexible postgres version

- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/BaseResourceCreateStep.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStep.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/utils/FlightUtils.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/BaseResourceCreateStepTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/delete/DeleteLandingZoneResourcesStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-1083
> handle azure interrupted exceptions

- service/src/main/java/bio/terra/landingzone/stairway/flight/CromwellStepsDefinitionProvider.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksCostOptimizationDataCollectionRulesStep.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksCostOptimizationDataCollectionRulesStepTest.java
https://broadworkbench.atlassian.net/browse/WOR-841
> WOR-841 Configure 30-minute data collection interval for Container Insights

- service/src/main/java/bio/terra/landingzone/common/utils/RetryRules.java
- service/src/main/java/bio/terra/landingzone/library/landingzones/definition/ResourceNameGenerator.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/LandingZoneDefaultParameters.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresqlDbStep.java
- service/src/test/java/bio/terra/landingzone/library/landingzones/TestArmResourcesFactory.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresqlDbStepTest.java
- service/src/test/resources/application-test.yml
We are changing the default region for our Azure offering to South Central US, and these updates were necessary to get the landing zone to deploy.
> [WOR-1228] Updates for using South Central US region

- service/src/main/java/bio/terra/landingzone/stairway/flight/create/AwaitCreateLandingZoneResourcesFlightStep.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlight.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightStep.java
- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreatePostgresqlDbStep.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneFlightTest.java
-Increase timeout for lz creation (60 minutes now) 
-do some tiny refactoring
> WOR-1211 Increase resource creation job timeout limit for landing zone creation

- service/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesReaderImpl.java
https://broadworkbench.atlassian.net/browse/WOR-1281
> stop logging so much

- service/src/main/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStep.java
- service/src/test/java/bio/terra/landingzone/stairway/flight/create/resource/step/CreateAksStepTest.java
WOR-1315
This particular change adjust name of the node resource group. Corresponding fix for cost report will be in BPM.
> WOR-1315 Calculate azure cost for billing project based on new format of AKS node resource group.

- buildSrc/build.gradle
- buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle
- buildSrc/src/main/groovy/bio.terra.landingzone.java-spring-library-conventions.gradle
- client/swagger.gradle
- library/build.gradle
- library/src/main/java/bio/terra/landingzone/job/LandingZoneJobBuilder.java
- library/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java
- library/src/main/java/bio/terra/landingzone/service/bpm/LandingZoneBillingProfileManagerService.java
- library/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamClient.java
- library/src/main/java/bio/terra/landingzone/service/iam/LandingZoneSamService.java
- library/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java
- service/build.gradle
- service/gradle/generators.gradle
- service/src/main/java/bio/terra/lz/futureservice/app/LandingZoneApplication.java
- service/src/main/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiController.java
- service/src/main/resources/application.yml
- testharness/build.gradle
https://broadworkbench.atlassian.net/browse/WOR-1394
> WOR-1394 update to spring3, open telemetry, etc

- library/src/main/java/bio/terra/landingzone/stairway/flight/exception/translation/FlexiblePostgresRegionRestrictedOfferExceptionRule.java
- library/src/main/java/bio/terra/landingzone/stairway/flight/exception/translation/FlightExceptionTranslator.java
- library/src/test/java/bio/terra/landingzone/stairway/flight/exception/translation/ExceptionFixtures.java
- library/src/test/java/bio/terra/landingzone/stairway/flight/exception/translation/FlexiblePostgresRegionRestrictedOfferExceptionRuleTest.java
- library/src/test/java/bio/terra/landingzone/stairway/flight/exception/translation/FlightExceptionTranslatorTest.java
Add handler specific to flexible postgres region restrictions issue
> WOR-1409 Improve error handling for long running operation error

- .github/workflows/build-and-test.yml
- service/build.gradle
> WOR-1421 Landing zone service failing to start due to configuration issue.

- .github/dependabot.yml
Need to also ignore patch releases per https://github.com/DataBiosphere/terra-landing-zone-service/pull/389.
WOR-1449 is to investigate and upgrade/remove the ignores.
> [WOR-1449] Ignore patch releases of spring-boot-plugin also.

- .github/workflows/build-and-test.yml
- README.md
- service/build.gradle
Integrate [minniekenny](https://minnie-kenny.readthedocs.io/en/latest/) with build pipeline.
> WOR-1487 Setup minniekenny in LZS.

- .github/workflows/build-and-test.yml
- .github/workflows/tag-publish.yml
This PR:
-Enables Trivy security scanner of LZS docker image
-Enables publishing LZS docker image
> WOR-1486 Enable docker build and docker image scan.

- service/build.gradle
- service/src/main/java/bio/terra/lz/futureservice/app/StartupInitializer.java
- service/src/main/java/bio/terra/lz/futureservice/app/configuration/SentryConfiguration.java
- service/src/main/java/bio/terra/lz/futureservice/app/controller/GlobalExceptionHandler.java
- service/src/main/resources/application.yml
JIRA: [WOR-1493](https://broadworkbench.atlassian.net/browse/WOR-1493)
This PR:
-adds Sentry integration. 5xx errors will go to Sentry.
Corresponding helm change will be covered in the following ticket [WOR-1142](https://broadworkbench.atlassian.net/browse/WOR-1142)
[WOR-1493]: https://broadworkbench.atlassian.net/browse/WOR-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WOR-1142]: https://broadworkbench.atlassian.net/browse/WOR-1142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> WOR-1493 Integrate Sentry into LZS.

- .github/workflows/build-and-test.yml
- service/src/test/java/bio/terra/lz/futureservice/app/LandingZoneApplicationTests.java
- service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java
- service/src/test/java/bio/terra/lz/futureservice/app/controller/PublicApiControllerTest.java
- service/src/test/java/bio/terra/lz/futureservice/common/BaseSpringUnitTest.java
This PR adds configuration to run service level unit tests for pull request.
> [WOR-1576] Run service level unit tests on pull request.

- .github/workflows/tag-publish.yml
- service/gradle/publishing.gradle
This PR:
-adds new steps in 'Publish' workflow to let Sherlock knows about new Landing Zone app version.
> WOR-1142 terraform/helmfile changes for landing zone service

- service/src/main/resources/application.yml
Re-use existing environment variables. Similar to other projects.
> WOR-1595 Setup project in Sentry for LZS

- service/src/main/resources/application.yml
> WOR-1634 Adjust LZ config to include ingress configuration.

- library/src/main/java/bio/terra/landingzone/library/landingzones/management/ResourcesReaderImpl.java
- library/src/test/java/bio/terra/landingzone/stairway/flight/create/CreateLandingZoneResourcesFlightIntegrationTest.java
- service/src/test/java/bio/terra/lz/futureservice/app/controller/LandingZoneApiControllerTest.java
Resources are not returning in our listByTag call for unknown reasonse. This is trying a shift to reading all the resources in a given resource group and filtering by tag locally.
> [PROD-952] Shift to reading all resources and filtering by tag locally

- .github/workflows/verify_consumer_pacts.yaml
- service/gradle/testing.gradle
We need a provider side webhook for the can-i-deploy job to run.
> [WOR-1119] Add verify_consumer_pacts workflow for can-i-deploy webhook

- buildSrc/src/main/groovy/bio.terra.landingzone.java-common-conventions.gradle
- library/build.gradle
[Successful source clear run](https://github.com/broadinstitute/dsp-appsec-sourceclear-github-actions/actions/runs/9097041652/job/25003959679)
> Bump bouncy-castle to pull in fix for CVE

- .github/workflows/consumer_contract_tests.yml
- .github/workflows/verify_consumer_pacts.yaml
- service/src/test/java/bio/terra/lz/futureservice/pact/provider/LandingZoneServicePactProviderTest.java
Follow on to https://github.com/DataBiosphere/terra-workspace-manager/pull/1751
> [WOR-1671] Update pacticipant

- library/src/main/java/bio/terra/landingzone/job/LandingZoneJobService.java
- library/src/test/java/bio/terra/landingzone/job/LandingZoneJobServiceTest.java
fix in https://broadworkbench.atlassian.net/browse/WOR-1765 to do the right equality check
> WOR-1765 do the right equality check
